In [2]:
import numpy
numpy.version.full_version

'1.12.1'

In [4]:
import numpy as np
a = np.array([0,1,2,3,4,5])
a

array([0, 1, 2, 3, 4, 5])

In [68]:
# 配列の次元数の大きさ
a.ndim

1

In [11]:
# 配列が２次元の場合
b = np.array([[1, 3, 5], [2, 4, 6], [7,8,9]])
b.ndim

2

In [12]:
# 配列の各次元の大きさ
a.shape

(6,)

In [13]:
# ２次元配列の場合
b.shape

(3, 3)

In [16]:
# 配列を２次元の行列に変換
# 第一引数: 次元数、第二引数各次元の要素数
# 因みに要素数が足りなかったりするとエラー
c = a.reshape(2, 3)
c

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
c.ndim

2

In [74]:
# 因みに三次元はこんなの
d = np.array([[[1],[3], [5]], [[2], [4], [6]]])
d

array([[[1],
        [3],
        [5]],

       [[2],
        [4],
        [6]]])

In [75]:
d.ndim

3

In [76]:
c[1][0] = 77
c

array([[ 0,  1,  2],
       [77,  4,  5]])

In [77]:
# c = a.reshape(2, 3) より a も同様な修正が行われるため注意が必要
a

array([ 0,  1,  2, 77,  4,  5])

In [78]:
# .copy() とやると e を修正しても a は修正されない
e = a.reshape(3,2).copy()
e

array([[ 0,  1],
       [ 2, 77],
       [ 4,  5]])

In [79]:
e[1][0] = -99
e

array([[  0,   1],
       [-99,  77],
       [  4,   5]])

In [80]:
a

array([ 0,  1,  2, 77,  4,  5])

In [81]:
# 演算は各要素に対して行われる
a * 2

array([  0,   2,   4, 154,   8,  10])

In [82]:
a ** 2

array([   0,    1,    4, 5929,   16,   25])

In [83]:
# Python のリストだと要素が増える
[0,1,2,3,4,5] * 2

[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]

In [84]:
# 二乗はエラー
[0,1,2,3,4,5] ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [85]:
np.array([2,3,4])

array([2, 3, 4])

In [86]:
# 要素に対して配列でアクセス可能
a[np.array([2,3,4])]

array([ 2, 77,  4])

In [87]:
# 各要素に対して条件の結果を簡単に得られる
a > 4

array([False, False, False,  True, False,  True], dtype=bool)

In [89]:
# 条件に合う要素だけ取り出すことが可能
a[a > 4]

array([77,  5])

In [90]:
# clip 関数を使うと、配列の要素を指定された値（上限と下限）に収まるように修正可能
a.clip(1,4)

array([1, 1, 2, 4, 4, 4])

In [98]:
# Numpy のインデックス操作は、テキストファイルから読み込んだデータを扱いやすい形に整形するときに有効
# データには欠損値や不適切な値が含まれることが多くある
# こういった時、numpy.NAN を用いる
f = np.array([1, 2, np.NAN, 3, 5])
f

array([  1.,   2.,  nan,   3.,   5.])

In [99]:
# 各要素が nan かどうか
np.isnan(f)

array([False, False,  True, False, False], dtype=bool)

In [100]:
# nan でない要素だけを取得
f[~np.isnan(f)]

array([ 1.,  2.,  3.,  5.])

In [101]:
# f の要素の nan の値を、nan 以外の要素の平均値とする
np.mean(f[~np.isnan(f)])

2.75

In [ ]:
# 処理速度（省略）
# Python のリストと比較した場合、計算速度がおよそ 3.5 倍